### ISSUE TITLE
Feature: Support Redirect payment type

### ISSUE THREAD

**Issue by indykoning** [MultiSafepay/magento2-graphql#7]
We are in the process of migrating payment methods from using Magento's rest API to using GraphQL in our checkout.
Frontend-wise we cannot migrate without forcing our user to also use Payment components even though payment type is set to redirect.
![image](https://github.com/user-attachments/assets/33eee939-ceb9-4b6b-a817-0e8719add5c6)

This is because https://github.com/MultiSafepay/magento2-graphql/blob/master/Model/PaymentAdditionalDataProvider.php#L66 forces these parameters to also be filled without checking for payment type of the payment provider

It would be a nice solution to check wether the payment type before checking the additional data that's sent as that would not be necessary if it's redirect.

**Comment by vinodsowdagar** [comment]
Hi @indykoning ,

Thank you for the request, we are going to look into it and come back to you later.

**Comment by indykoning** [comment]
Above are 2 PRs that attempt to solve this behaviour in 2 different ways as it is not only the redirect option that suffers from this.
Hopefully they'll help looking into it

**Comment by indykoning** [comment]
Hi @vinodsowdagar,
Do you have an update regarding progress on this issue, or the PRs linked to this issue?

**Comment by vinodsowdagar** [comment]
Hi @indykoning ,

The change in PR https://github.com/MultiSafepay/magento2-graphql/pull/9/ looks to be the easiest solution. Thanks!
We've already added the change internally and it will be added in the next release.

We are expecting to create the release next week. I'll keep you updated in the meantime.

**Comment by vinodsowdagar** [comment]
Hi @indykoning ,

We've released your fix already: https://github.com/MultiSafepay/magento2-graphql/releases/tag/4.0.1
I'm closing this issue and related PR. Thanks again for your contribution!
